"use client"

import { useMemo, useState } from "react"
import Link from "next/link"
import { ArrowUpRight, Search, X } from "lucide-react"
import { projects } from "@/lib/hardcoded"
import Animated from "@/components/Animated"

const categories = ["All", "Web App", "Mobile App", "Backend", "UI/UX"]
export default function ProjectsPage() { const [category, setCategory] = useState("All"); const [query, setQuery] = useState(""); const filtered = useMemo(() => projects.filter(p => (category === "All" || p.category === category) && `${p.title} ${p.description} ${p.tags.join(" ")}`.toLowerCase().includes(query.toLowerCase())), [category, query]); return <main className="index-page"><section className="route-wrap index-hero"><Animated><p className="route-kicker">Projects / 03</p><h1>Selected work, with the rough edges left in.</h1><p className="route-lede">A record of applications and experiments built across frontend, backend, and mobile. Browse by category or search for a tool.</p></Animated></section><section className="route-wrap work-controls"><label><Search size={17}/><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Search projects" /></label><div>{categories.map(item => <button key={item} className={category === item ? "selected" : ""} onClick={() => setCategory(item)}>{item}</button>)}{query && <button aria-label="Clear search" onClick={() => setQuery("")}><X size={15}/></button>}</div></section><section className="route-wrap work-grid" aria-live="polite">{filtered.map((project, index) => <Animated key={project.id} delay={index * .06}><Link href={`/projects/${project.id}`} className="work-card"><div className="work-card-top"><span>0{index + 1}</span><span>{project.status}</span></div><h2>{project.title}</h2><p>{project.description}</p><div className="work-card-bottom"><span>{project.category}</span><ArrowUpRight size={18}/></div></Link></Animated>)}{filtered.length === 0 && <p className="empty-copy">Nothing found. Try a different word or category.</p>}</section></main> }
