import { Server } from "http"
import { Code, Layout, Database, Smartphone, Sparkles, Palette, Globe, Cpu, Phone } from "lucide-react"

const testimonials = [
    {
        id: 1,
        name: "Sarah Johnson",
        role: "CTO at TechStart",
        image: "/placeholder.svg?height=100&width=100",
        content:
            "Working with Charles was a game-changer for our project. Their technical expertise and problem-solving skills helped us launch our platform ahead of schedule. The code quality was exceptional, and they were always available to answer questions.",
        rating: 5,
    },
    {
        id: 2,
        name: "Michael Chen",
        role: "Product Manager at InnovateCorp",
        image: "/placeholder.svg?height=100&width=100",
        content:
            "Charles delivered beyond our expectations. They not only implemented all the features we requested but also suggested improvements that significantly enhanced the user experience. Their attention to detail and commitment to quality is remarkable.",
        rating: 5,
    },
    {
        id: 3,
        name: "Emily Rodriguez",
        role: "Founder at DesignHub",
        image: "/placeholder.svg?height=100&width=100",
        content:
            "I was impressed by Charles's ability to translate our design concepts into a fully functional website. Their understanding of both design principles and technical implementation made the collaboration seamless. I would definitely work with them again.",
        rating: 5,
    },
    {
        id: 4,
        name: "David Kim",
        role: "Lead Developer at WebSolutions",
        image: "/placeholder.svg?height=100&width=100",
        content:
            "As a fellow developer, I can attest to the quality of Charles's code. Clean, well-documented, and efficient. They're also great at knowledge sharing and mentoring junior team members. A true professional in every sense.",
        rating: 5,
    },
    {
        id: 5,
        name: "Lisa Patel",
        role: "Marketing Director at GrowthLabs",
        image: "/placeholder.svg?height=100&width=100",
        content:
            "Charles helped us implement complex analytics tracking and optimization for our marketing campaigns. Their technical insights significantly improved our conversion rates. They explain technical concepts clearly to non-technical team members.",
        rating: 5,
    },
]

const services = [
    {
        icon: Code,
        title: "Web Development",
        description:
            "Custom web applications built with modern frameworks and best practices for optimal performance and user experience.",
        features: ["AngularJs", "Next.js", "TypeScript", "Responsive Design", "SEO Optimization"],
    },
    {
        icon: Server,
        title: "Backend Development",
        description:
            "Robust server-side solutions that power your applications with secure, scalable, and efficient code.",
        features: ["Node/Express", "NestJs", "API Development", "Authentication", "Database Integration"],
    },
    {
        icon: Layout,
        title: "UI/UX Design",
        description:
            "User-centered design that combines aesthetics with functionality to create intuitive and engaging interfaces.",
        features: ["Prototyping", "User Testing", "Design Systems"],
    },
    {
        icon: Database,
        title: "Database Design",
        description: "Efficient database architecture that ensures data integrity, security, and optimal performance.",
        features: ["Schema Design", "Query Optimization", "Data Migration", "NoSQL/SQL"],
    },
    {
        icon: Smartphone,
        title: "Mobile Development",
        description: "Cross-platform mobile applications that provide native-like experiences with a single codebase.",
        features: ["React Native", "Push Notifications", "Offline Support", "Expo"],
    },
    {
        icon: Sparkles,
        title: "Performance Optimization",
        description: "Enhance your existing applications with improved speed, efficiency, and user experience.",
        features: ["Code Auditing", "Load Time Reduction", "Caching Strategies", "Bundle Optimization"],
    },
]

const TeckStack: string[] = [
    "Angular", "Next.js", "Firebase", "Appwrite", "Tailwind", "ExpressJs", "NestJS",
    "PHP", "Laravel", "Typecript", "Javascript", "HTML", "CSS", "Expo", "React Native",
    "MongoDB", "MySQL", "PostgreSQL", "Git", "Figma", "AWS", "Vercel",
    "Bootstrap"
]
const skillCategories = [
    {
        id: "frontend",
        name: "Frontend",
        icon: Code,
        skills: [
            { name: "Angular", level: 65 },
            { name: "Next.js", level: 80 },
            { name: "TypeScript", level: 65 },
            { name: "Tailwind CSS", level: 80 },
            { name: "JavaScript", level: 65 },
            { name: "HTML/CSS", level: 85 },
        ],
    },
    {
        id: "backend",
        name: "Backend",
        icon: Server,
        skills: [
            { name: "Express", level: 80 },
            { name: "NestJs", level: 75 },
            { name: "REST API", level: 90 },
            { name: "Laravel", level: 60 },
            { name: "Authentication", level: 85 },
            { name: "Node.js", level: 70 },
            { name: 'JWT', level: 80 }
        ],
    },
    {
        id: "design",
        name: "Design",
        icon: Palette,
        skills: [
            { name: "Figma", level: 55 },
            { name: "Responsive Design", level: 90 },
            { name: "Prototyping", level: 50 },

        ],
    },
    {
        id: "database",
        name: "Database",
        icon: Database,
        skills: [
            { name: "MongoDB", level: 85 },
            { name: "PostgreSQL", level: 80 },
            { name: "MySQL", level: 75 },
            { name: "Firebase", level: 85 },
            { name: "Appwrite", level: 70 },
            { name: "Supabase", level: 80 },
        ],
    },
    {
        id: "deployment",
        name: "Deployment",
        icon: Globe,
        skills: [
            { name: "AWS", level: 40 },
            { name: "Vercel", level: 65 },
            { name: 'Render', level: 60 }
        ],
    },
    {
        id: "Mobile",
        name: "Mobile",
        icon: Phone,
        skills: [
            {
                name: "React native",
                level: 65
            },
            {
                name: "Expo",
                level: 65
            },
            {
                name: "Nativewind",
                level: 80
            }
        ]
    },
    {
        id: "other",
        name: "Other",
        icon: Cpu,
        skills: [
            { name: "Git", level: 70 },
            { name: "Testing", level: 80 },
            { name: "Agile", level: 85 },
            { name: "Performance", level: 80 },
            { name: "SEO", level: 75 },
            { name: "Accessibility", level: 85 },
        ],
    }
]

export {
    skillCategories,
    services,
    TeckStack,
    testimonials
}

export interface Project {
    id: number;
    title: string;
    description: string;
    category: string;
    image: string;
    section: Array<string>;
    tags: Array<string>;
    featured: boolean;
    demoUrl: string;
    githubUrl: string;
    otherimages: Array<string>;
    inDevelopment: boolean;
    rebranding: boolean,
    status: 'Active' | 'Paused' | 'Discontinued'


}

const activeProjects: Project[] = [
    {
        id: 1,
        title: "Learn it Academy",
        description: "A institute based learning management system",
        image: "/assets/projects/learnit-base.png",
        category: "Web App",
        section: ['Frontend', 'Backend'],
        tags: ["Next.js", "Appwrite", "Tailwind", 'Tanstack Query', 'Zustand', 'shadcn', "TypeScript"],
        demoUrl: "https://learnit-academy.vercel.app",
        githubUrl: "https://github.com/Alaric-senpai/LearnIT",
        featured: true,
        otherimages: ['/assets/projects/learnit-1.png', '/assets/projects/learnit-2.png', '/assets/projects/learnit-4.png', '/assets/projects/learnit-4.png', '/assets/projects/learnit-5.png'],
        inDevelopment: true,
        rebranding: true,
        status: 'Active'
    },
    {
        id: 2,
        title: 'Entzone',
        description: 'A movie listing and torrenting platform powered by YTS.mx api',
        image: '/assets/projects/entzone-base.png',
        category: 'Web App',
        section: ['Frontend'],
        tags: ['HTML', 'CSS', 'JavaScript', 'YTS API'],
        demoUrl: '',
        featured: false,
        otherimages: ['/assets/projects/entzone-1.png', '/assets/projects/entzone-2.png'],
        githubUrl: "https://github.com/Alaric-senpai/Entzone",
        inDevelopment: true,
        rebranding: false,
        status: "Active"
    },
    {
        id: 3,
        title: "Echoplain",
        description: "A simple nextjs firebase blog",
        category: "Web app",
        image: "/assets/projects/echoplain-base.png",
        section: ['Frontend'],
        tags: ['Next.js', 'Firebase', 'shadcn', 'Tailwind', 'TypeScript', 'Auth'],
        featured: true,
        demoUrl: "https://echoplain.vercel.app",
        githubUrl: "https://github.com/Alaric-senpai/echoplain",
        otherimages: ['/assets/projects/echoplain-1.png', '/assets/projects/echoplain-2.png', '/assets/projects/echoplain-3.png', '/assets/projects/echoplain-4.png', '/assets/projects/echoplain-5.png', '/assets/projects/echoplain-6.png', '/assets/projects/echoplain-7.png'],
        inDevelopment: true,
        rebranding: false,
        status: "Active"
    },
    {
        id: 4,
        title: "Habit Bloom",
        description: "A clean, gamified offline app for tracking your daily habits and visualizing consistency. Think of it as a pocket habit gardener: each habit you keep grows a little 'bloom' icon that thrives the longer you stay consistent.",
        category: "Mobile App",
        image: "/assets/projects/preview-missing.png",
        section: ['Mobile'],
        tags: ['React Native', 'Expo', 'TypeScript', 'Drizzle ORM', 'SQLite', 'Gamification', 'Habit Tracker', 'Goals', 'Personal Growth'],
        featured: true,
        demoUrl: "",
        githubUrl: "https://github.com/Alaric-senpai/Habit-bloom",
        otherimages: [],
        inDevelopment: true,
        rebranding: false,
        status: "Active"
    },
    {
        id: 5,
        title: "Streamy",
        description: "A movie streaming mobile application",
        category: "Mobile App",
        image: "/assets/projects/preview-missing.png",
        section: ['Mobile'],
        tags: ['React Native', 'Expo', 'TypeScript', 'Video', 'Streaming'],
        featured: true,
        demoUrl: "",
        githubUrl: "https://github.com/Alaric-senpai/streamy",
        otherimages: [],
        inDevelopment: true,
        rebranding: false,
        status: "Active"
    },

    {
        id: 7,
        title: "Pesa Sync",
        description: "A simple offline finance tracker",
        category: "Mobile App",
        image: "/assets/projects/preview-missing.png",
        section: ['Mobile'],
        tags: ['React Native', 'Expo', 'TypeScript', 'Finance', 'Offline'],
        featured: false,
        demoUrl: "",
        githubUrl: "https://github.com/Alaric-senpai/pesa-sync",
        otherimages: [],
        inDevelopment: true,
        rebranding: false,
        status: "Active"
    },
    // {
    //     id: 8,
    //     title: "CBC LMS",
    //     description: "A competency based curriculum learning management system API",
    //     category: "Backend",
    //     image: "/assets/projects/cbclms-base.png",
    //     section: ['Backend'],
    //     tags: ['TypeScript', 'NestJS', 'PostgreSQL', 'Prisma ORM', 'LMS', 'CBC', 'API'],
    //     featured: false,
    //     demoUrl: "",
    //     githubUrl: "https://github.com/Alaric-senpai/cbclms",
    //     otherimages: [],
    //     inDevelopment: true,
    //     rebranding: false,
    //     status: "Active"
    // },
    // {
    //     id: 9,
    //     title: "Crafted",
    //     description: "A crafted web application",
    //     category: "Web App",
    //     image: "/assets/projects/crafted-base.png",
    //     section: ['Frontend'],
    //     tags: ['TypeScript', 'Next.js'],
    //     featured: false,
    //     demoUrl: "",
    //     githubUrl: "https://github.com/Alaric-senpai/crafted",
    //     otherimages: [],
    //     inDevelopment: true,
    //     rebranding: false,
    //     status: "Active"
    // },
    // {
    //     id: 10,
    //     title: "Portfolio Master",
    //     description: "Portfolio master backend for CMS support with Appwrite, Next.js and shadcn",
    //     category: "Web App",
    //     image: "/assets/projects/portfolio-master-base.png",
    //     section: ['Frontend', 'Backend'],
    //     tags: ['TypeScript', 'Next.js', 'Appwrite', 'shadcn', 'CMS'],
    //     featured: false,
    //     demoUrl: "",
    //     githubUrl: "https://github.com/Alaric-senpai/portfoliomaster",
    //     otherimages: [],
    //     inDevelopment: true,
    //     rebranding: false,
    //     status: "Active"
    // },
    // {
    //     id: 11,
    //     title: "Strategem Mobile",
    //     description: "Mobile version of the Strategem project management tool",
    //     category: "Mobile App",
    //     image: "/assets/projects/strategem-mobile-base.png",
    //     section: ['Mobile'],
    //     tags: ['TypeScript', 'React Native', 'Expo', 'Project Management'],
    //     featured: false,
    //     demoUrl: "",
    //     githubUrl: "https://github.com/Alaric-senpai/strategem-mobile",
    //     otherimages: [],
    //     inDevelopment: true,
    //     rebranding: false,
    //     status: "Active"
    // },
    // {
    //     id: 12,
    //     title: "Sleazy",
    //     description: "Mobile application with custom toast notification system",
    //     category: "Mobile App",
    //     image: "/assets/projects/sleazy-base.png",
    //     section: ['Mobile'],
    //     tags: ['React Native', 'Expo', 'TypeScript', 'Custom UI'],
    //     featured: false,
    //     demoUrl: "",
    //     githubUrl: "https://github.com/Alaric-senpai/sleazy",
    //     otherimages: [],
    //     inDevelopment: true,
    //     rebranding: false,
    //     status: "Active"
    // },
    // {
    //     id: 13,
    //     title: "Portfolio Mobile App",
    //     description: "Mobile version of developer portfolio",
    //     category: "Mobile App",
    //     image: "/assets/projects/portfolio-mobile-base.png",
    //     section: ['Mobile'],
    //     tags: ['TypeScript', 'React Native', 'Expo'],
    //     featured: false,
    //     demoUrl: "",
    //     githubUrl: "https://github.com/Alaric-senpai/portfolio-mobile-app",
    //     otherimages: [],
    //     inDevelopment: true,
    //     rebranding: false,
    //     status: "Active"
    // },
    {
        id: 14,
        title: "Green Bin",
        description: "A smart waste management system mobile app",
        category: "Mobile App",
        image: "/assets/projects/preview-missing.png",
        section: ['Mobile'],
        tags: ['TypeScript', 'React Native', 'Expo', 'Waste Management', 'Environment'],
        featured: false,
        demoUrl: "",
        githubUrl: "https://github.com/Alaric-senpai/Green-Bin",
        otherimages: [],
        inDevelopment: false,
        rebranding: false,
        status: "Paused"
    },
    {
        id: 15,
        title: "Lynkr",
        description: "A link management application",
        category: "Mobile app",
        image: "/assets/projects/preview-missing.png",
        section: ['Mobile'],
        tags: ['TypeScript', 'Next.js', 'Link Management'],
        featured: false,
        demoUrl: "",
        githubUrl: "https://github.com/Alaric-senpai/lynkr",
        otherimages: [],
        inDevelopment: true,
        rebranding: false,
        status: "Active"
    },
    {
        id: 16,
        title: "Cartnest API",
        description: "An e-commerce API",
        category: "Backend",
        image: "/assets/projects/cartnest-base.png",
        section: ['Backend'],
        tags: ['JavaScript', 'Node.js', 'Express.js', 'API', 'E-commerce'],
        featured: false,
        demoUrl: "",
        githubUrl: "https://github.com/Alaric-senpai/cartnest_api",
        otherimages: [],
        inDevelopment: false,
        rebranding: false,
        status: "Paused"
    },
    {
        id: 17,
        title: "Flux",
        description: "A movie streaming platform",
        category: "Web App",
        image: "/assets/projects/flux-base.png",
        section: ['Frontend'],
        tags: ['TypeScript', 'Next.js', 'Video Streaming', 'Movies'],
        featured: false,
        demoUrl: "https://flux-zeta-ten.vercel.app",
        githubUrl: "https://github.com/Alaric-senpai/flux",
        otherimages: [
            "/assets/projects/flux-1.png",
            "/assets/projects/flux-2.png",
            "/assets/projects/flux-3.png",
            "/assets/projects/flux-4.png",
            "/assets/projects/flux-5.png",
            "/assets/projects/flux-6.png",
            "/assets/projects/flux-7.png",
            "/assets/projects/flux-8.png",
            "/assets/projects/flux-9.png"
        ],
        inDevelopment: false,
        rebranding: false,
        status: "Active"
    },
    {
        id: 18,
        title: "CartNest",
        description: "A simple ecommerce web app",
        category: "Web App",
        image: "/assets/projects/cartnest-base.png",
        section: ['Frontend'],
        tags: ['TypeScript', 'Angular', 'E-commerce'],
        featured: false,
        demoUrl: "https://cartnest.vercel.app",
        githubUrl: "https://github.com/Alaric-senpai/CartNest",
        otherimages: [
            "/assets/projects/cartnest-1.png",
            "/assets/projects/cartnest-2.png"
        ],
        inDevelopment: false,
        rebranding: false,
        status: "Discontinued"
    },
    // {
    //     id: 19,
    //     title: "Kaziflow",
    //     description: "A progress tracking tool for managing interns and attachés efficiently. It simplifies attendance tracking, task assignment, and report supervision.",
    //     category: "Web App",
    //     image: "/assets/projects/kaziflow-base.png",
    //     section: ['Frontend', 'Backend'],
    //     tags: ['CSS', 'Next.js', 'Appwrite', 'Attendance', 'Task Management'],
    //     featured: true,
    //     demoUrl: "",
    //     githubUrl: "https://github.com/Alaric-senpai/kaziflow",
    //     otherimages: [],
    //     inDevelopment: true,
    //     rebranding: false,
    //     status: "Active"
    // },
    // {
    //     id: 20,
    //     title: "Webcraft",
    //     description: "Web development tools and utilities",
    //     category: "Web App",
    //     image: "/assets/projects/webcraft-base.png",
    //     section: ['Frontend'],
    //     tags: ['HTML', 'CSS', 'JavaScript'],
    //     featured: false,
    //     demoUrl: "",
    //     githubUrl: "https://github.com/Alaric-senpai/webcraft",
    //     otherimages: [],
    //     inDevelopment: false,
    //     rebranding: false,
    //     status: "Discontinued"
    // },
    {
        id: 21,
        title: "VetConnect",
        description: "VetConnect is a lightweight, PHP-based veterinary clinic management system built for small to mid-sized vet practices. It offers appointment scheduling, medical records tracking, and pet management.",
        category: "Web App",
        image: "/assets/projects/vetconnect-base.png",
        section: ['Frontend', 'Backend'],
        tags: ['PHP', 'Tailwind CSS', 'Veterinary', 'Management System'],
        featured: false,
        demoUrl: "https://vetconnect.ct.ws",
        githubUrl: "https://github.com/Alaric-senpai/Vetconnect",
        otherimages: [
            "/assets/projects/vetconnect-1.png",
            "/assets/projects/vetconnect-2.png",
            "/assets/projects/vetconnect-3.png",
        ],
        inDevelopment: true,
        rebranding: true,
        status: "Active"
    },
    // {
    //     id: 22,
    //     title: "EduBridge LMS Demo UI",
    //     description: "Demo UI for EduBridge Learning Management System",
    //     category: "Web App",
    //     image: "/assets/projects/edubridge-base.png",
    //     section: ['Frontend'],
    //     tags: ['TypeScript', 'Next.js', 'LMS', 'Education'],
    //     featured: false,
    //     demoUrl: "https://edums-seven.vercel.app",
    //     githubUrl: "https://github.com/Alaric-senpai/edubridge-lms-demo-ui",
    //     otherimages: [],
    //     inDevelopment: false,
    //     rebranding: false,
    //     status: "Paused"
    // },
    // {
    //     id: 23,
    //     title: "Remix",
    //     description: "A Remix framework based web application",
    //     category: "Web App",
    //     image: "/assets/projects/remix-base.png",
    //     section: ['Frontend'],
    //     tags: ['TypeScript', 'Remix'],
    //     featured: false,
    //     demoUrl: "",
    //     githubUrl: "https://github.com/Alaric-senpai/remix",
    //     otherimages: [],
    //     inDevelopment: false,
    //     rebranding: false,
    //     status: "Paused"
    // },
    {
        id: 24,
        title: "ScriptVerse",
        description: "A scripting and code sharing platform",
        category: "Web App",
        image: "/assets/projects/scriptverse-base.png",
        section: ['Frontend'],
        tags: ['TypeScript', 'Next.js', 'Code Sharing'],
        featured: false,
        demoUrl: "https://script-verse-bay.vercel.app",
        githubUrl: "https://github.com/Alaric-senpai/ScriptVerse",
        otherimages: [
            "/assets/projects/scriptverse-1.png",
            "/assets/projects/scriptverse-2.png",
            "/assets/projects/scriptverse-3.png"
        ],
        inDevelopment: false,
        rebranding: false,
        status: "Active"
    },
    // {
    //     id: 25,
    //     title: "Codexa Functions",
    //     description: "Appwrite functions for Codexa platform",
    //     category: "Backend",
    //     image: "/assets/projects/codexa-functions-base.png",
    //     section: ['Backend'],
    //     tags: ['JavaScript', 'Appwrite', 'Functions', 'Serverless'],
    //     featured: false,
    //     demoUrl: "",
    //     githubUrl: "https://github.com/Alaric-senpai/codexa_functions_appwrite",
    //     otherimages: [],
    //     inDevelopment: false,
    //     rebranding: false,
    //     status: "Paused"
    // },
    // {
    //     id: 26,
    //     title: "Codexa",
    //     description: "A learner oriented teaching platform",
    //     category: "Web App",
    //     image: "/assets/projects/codexa-base.png",
    //     section: ['Frontend', 'Backend'],
    //     tags: ['TypeScript', 'Next.js', 'Appwrite', 'Education', 'Learning Platform'],
    //     featured: false,
    //     demoUrl: "",
    //     githubUrl: "https://github.com/Alaric-senpai/Codexa",
    //     otherimages: [],
    //     inDevelopment: false,
    //     rebranding: false,
    //     status: "Paused"
    // },
    {
        id: 27,
        title: "SmAnime Mobile App",
        description: "Mobile version of SmAnime anime streaming platform",
        category: "Mobile App",
        image: "/assets/projects/smanime-base.png",
        section: ['Mobile'],
        tags: ['TypeScript', 'React Native', 'Expo', 'Anime'],
        featured: false,
        demoUrl: "",
        githubUrl: "https://github.com/Alaric-senpai/smanime-mbile-app",
        otherimages: [],
        inDevelopment: true,
        rebranding: false,
        status: "Active"
    },
    {
        id: 28,
        title: "SmAnime",
        description: "An anime listing platform powered by Jikan API. streaming coming soon",
        category: "Web App",
        image: "/assets/projects/smanime-base.png",
        section: ['Frontend'],
        tags: ['TypeScript', 'Next.js', 'Anime', 'Streaming', 'Jikan api'],
        featured: false,
        demoUrl: "https://smanime.vercel.app",
        githubUrl: "https://github.com/Alaric-senpai/smanime",
        otherimages: [
            "/assets/projects/smanime-1.png",
            "/assets/projects/smanime-2.png",
            "/assets/projects/smanime-3.png"
        ],
        inDevelopment: true,
        rebranding:true,
        status: "Active"
    },
    {
        id: 29,
        title: "Hueforge",
        description: "A color manipulation and design tool",
        category: "Web App",
        image: "/assets/projects/hueforge-base.png",
        section: ['Frontend'],
        tags: ['TypeScript', 'Next.js', 'Color Tool', 'Design'],
        featured: false,
        demoUrl: "https://hueforge.vercel.app",
        githubUrl: "https://github.com/Alaric-senpai/Hueforge",
        otherimages: [
            "/assets/projects/hueforge-1.png",
            "/assets/projects/hueforge-2.png",
            "/assets/projects/hueforge-3.png"
            
        ],
        inDevelopment: false,
        rebranding: false,
        status: "Active"
    },
    // {
    //     id: 30,
    //     title: "LMS API",
    //     description: "Learning Management System API",
    //     category: "Backend",
    //     image: "/assets/projects/lms-api-base.png",
    //     section: ['Backend'],
    //     tags: ['JavaScript', 'Node.js', 'API', 'LMS'],
    //     featured: false,
    //     demoUrl: "",
    //     githubUrl: "https://github.com/Alaric-senpai/lmsapi",
    //     otherimages: [],
    //     inDevelopment: false,
    //     rebranding: false,
    //     status: "Paused"
    // },
    // {
    //     id: 31,
    //     title: "Portfolio",
    //     description: "Developer portfolio built with Next.js, shadcn and Appwrite",
    //     category: "Web App",
    //     image: "/assets/projects/portfolio-base.png",
    //     section: ['Frontend'],
    //     tags: ['TypeScript', 'Next.js', 'shadcn', 'Appwrite', 'Portfolio'],
    //     featured: false,
    //     demoUrl: "",
    //     githubUrl: "https://github.com/Alaric-senpai/Portfolio",
    //     otherimages: [],
    //     inDevelopment: false,
    //     rebranding: false,
    //     status: "Paused"
    // },
    {
        id: 32,
        title: "ManageIt",
        description: "A simple project management tool",
        category: "Web App",
        image: "/assets/projects/preview-missing.png",
        section: ['Frontend'],
        tags: ['Inertia', 'Laravel', 'Project Management', ''],
        featured: false,
        demoUrl: "",
        githubUrl: "https://github.com/Alaric-senpai/ManageIt",
        otherimages: [],
        inDevelopment: false,
        rebranding: false,
        status: "Paused"
    },
    {
        id: 33,
        title: "Strategem",
        description: "The ultimate AI-powered project Navigator",
        category: "Web App",
        image: "/assets/projects/preview-missing.png",
        section: ['Frontend'],
        tags: ['TypeScript', 'Next.js', 'AI', 'Project Management'],
        featured: false,
        demoUrl: "",
        githubUrl: "https://github.com/Alaric-senpai/strategem",
        otherimages: [],
        inDevelopment: false,
        rebranding: false,
        status: "Paused"
    },
    {
        id: 34,
        title: "Viewlix",
        description: "A movie listing and discovery platform",
        category: "Web App",
        image: "/assets/projects/preview-missing.png",
        section: ['Frontend'],
        tags: ['TypeScript', 'Next.js', 'Movies', 'TMDB'],
        featured: false,
        demoUrl: "https://viewlix.vercel.app",
        githubUrl: "https://github.com/Alaric-senpai/Viewlix",
        otherimages: [],
        inDevelopment: false,
        rebranding: false,
        status: "Discontinued"
    },
    // {
    //     id: 35,
    //     title: "SkillMatch",
    //     description: "A skill matching platform",
    //     category: "Web App",
    //     image: "/assets/projects/skillmatch-base.png",
    //     section: ['Frontend'],
    //     tags: ['CSS', 'HTML', 'JavaScript', 'Skills'],
    //     featured: false,
    //     demoUrl: "",
    //     githubUrl: "https://github.com/Alaric-senpai/skillMatch",
    //     otherimages: [],
    //     inDevelopment: false,
    //     rebranding: false,
    //     status: "Discontinued"
    // },
    {
        id: 36,
        title: "Anime Tracker",
        description: "An anime listing app",
        category: "Web App",
        image: "/assets/projects/preview-missing.png",
        section: ['Frontend'],
        tags: ['TypeScript', 'Next.js', 'Anime'],
        featured: false,
        demoUrl: "",
        githubUrl: "https://github.com/Alaric-senpai/Animetracker",
        otherimages: [],
        inDevelopment: false,
        rebranding: false,
        status: "Discontinued"
    },
    // {
    //     id: 37,
    //     title: "Mock Interview Generator",
    //     description: "A real-time AI-driven mock interview platform with Next.js and Vapi AI, offering personalized prep sessions",
    //     category: "Web App",
    //     image: "/assets/projects/mock-interview-base.png",
    //     section: ['Frontend'],
    //     tags: ['TypeScript', 'Next.js', 'AI', 'Vapi', 'Interview'],
    //     featured: false,
    //     demoUrl: "https://beta.jsmastery.pro",
    //     githubUrl: "https://github.com/Alaric-senpai/mock_interview_generator",
    //     otherimages: [],
    //     inDevelopment: false,
    //     rebranding: false,
    //     status: "Paused"
    // },
    // {
    //     id: 38,
    //     title: "Integrity Trust Bank Loan System",
    //     description: "A loan management system for banking operations",
    //     category: "Web App",
    //     image: "/assets/projects/integrity-bank-base.png",
    //     section: ['Frontend', 'Backend'],
    //     tags: ['PHP', 'Banking', 'Loan Management', 'Finance'],
    //     featured: false,
    //     demoUrl: "https://integrity-trust-bank-loan-system.vercel.app",
    //     githubUrl: "https://github.com/Alaric-senpai/Integrity-trust-bank-loan-system",
    //     otherimages: [],
    //     inDevelopment: false,
    //     rebranding: false,
    //     status: "Discontinued"
    // },
    {
        id: 39,
        title: "Celestia",
        description: "A simple weather app using OpenMeteo API",
        category: "Web App",
        image: "/assets/projects/celestia-base.png",
        section: ['Frontend'],
        tags: ['TypeScript', 'Next.js', 'Weather API', 'Charts', 'Geolocation'],
        featured: false,
        demoUrl: "https://celestia-ebon.vercel.app",
        githubUrl: "https://github.com/Alaric-senpai/celestia",
        otherimages: [],
        inDevelopment: false,
        rebranding: false,
        status: "Active"
    },
    {
        id: 40,
        title: "Music Player",
        description: "A simple music player for local files. Runs only locally.",
        category: "Web App",
        image: "/assets/projects/preview-missing.png",
        section: ['Frontend'],
        tags: ['TypeScript', 'Next.js', 'Music', 'Audio'],
        featured: false,
        demoUrl: "",
        githubUrl: "https://github.com/Alaric-senpai/Musicplayer",
        otherimages: [],
        inDevelopment: false,
        rebranding: false,
        status: "Active"
    },
    {
        id: 41,
        title: "GitFinder",
        description: "A simple git finder UI to find users in GitHub using Octokit.js",
        category: "Web App",
        image: "/assets/projects/gitfinder-base.png",
        section: ['Frontend'],
        tags: ['TypeScript', 'Next.js', 'GitHub API', 'Octokit'],
        featured: false,
        demoUrl: "https://gitfinder-mu.vercel.app",
        githubUrl: "https://github.com/Alaric-senpai/Gitfinder",
        otherimages: [
            "/assets/projects/gitfinder-1.png",
            "/assets/projects/gitfinder-2.png",
            "/assets/projects/gitfinder-3.png",
            "/assets/projects/gitfinder-4.png"
        ],
        inDevelopment: false,
        rebranding: false,
        status: "Active"
    },
    // {
    //     id: 42,
    //     title: "StudyIO Backend",
    //     description: "A simple NestJS school API",
    //     category: "Backend",
    //     image: "/assets/projects/studyio-backend-base.png",
    //     section: ['Backend'],
    //     tags: ['TypeScript', 'NestJS', 'API', 'School Management'],
    //     featured: false,
    //     demoUrl: "",
    //     githubUrl: "https://github.com/Alaric-senpai/studyio_backend",
    //     otherimages: [],
    //     inDevelopment: false,
    //     rebranding: false,
    //     status: "Paused"
    // },
    // {
    //     id: 43,
    //     title: "StudyIO Frontend",
    //     description: "A simple school management system frontend",
    //     category: "Web App",
    //     image: "/assets/projects/studyio-frontend-base.png",
    //     section: ['Frontend'],
    //     tags: ['TypeScript', 'Next.js', 'School Management'],
    //     featured: false,
    //     demoUrl: "",
    //     githubUrl: "https://github.com/Alaric-senpai/studyio_nextjs_frontend",
    //     otherimages: [],
    //     inDevelopment: false,
    //     rebranding: false,
    //     status: "Paused"
    // },
    {
        id: 44,
        title: "MovieHub",
        description: "A movie discovery and listing platform",
        category: "Web App",
        image: "/assets/projects/moviehub-base.png",
        section: ['Frontend'],
        tags: ['TypeScript', 'Next.js', 'Movies', 'TMDB'],
        featured: false,
        demoUrl: "https://moviehub-seven.vercel.app",
        githubUrl: "https://github.com/Alaric-senpai/moviehub",
        otherimages: [],
        inDevelopment: false,
        rebranding: false,
        status: "Paused"
    },
    // {
    //     id: 45,
    //     title: "Map Class App",
    //     description: "An application for working with maps and geolocation",
    //     category: "Web App",
    //     image: "/assets/projects/map-class-base.png",
    //     section: ['Frontend'],
    //     tags: ['TypeScript', 'Next.js', 'Maps', 'Geolocation'],
    //     featured: false,
    //     demoUrl: "",
    //     githubUrl: "https://github.com/Alaric-senpai/map-class-app",
    //     otherimages: [],
    //     inDevelopment: false,
    //     rebranding: false,
    //     status: "Discontinued"
    // },
    {
        id: 46,
        title: "News Nexus",
        description: "A news aggregation and reading application",
        category: "Web App",
        image: "/assets/projects/preview-missing.png",
        section: ['Frontend'],
        tags: ['TypeScript', 'Angular', 'News API'],
        featured: false,
        demoUrl: "https://news-nexus-snowy.vercel.app",
        githubUrl: "https://github.com/Alaric-senpai/News-Nexus",
        otherimages: [],
        inDevelopment: false,
        rebranding: false,
        status: "Paused"
    },
    // {
    //     id: 47,
    //     title: "Evergreen",
    //     description: "An evergreen content platform",
    //     category: "Web App",
    //     image: "/assets/projects/evergreen-base.png",
    //     section: ['Frontend'],
    //     tags: ['HTML', 'CSS', 'JavaScript'],
    //     featured: false,
    //     demoUrl: "",
    //     githubUrl: "https://github.com/Alaric-senpai/Evergreen",
    //     otherimages: [],
    //     inDevelopment: false,
    //     rebranding: false,
    //     status: "Discontinued"
    // },
    // {
    //     id: 48,
    //     title: "House Listing Example",
    //     description: "A real estate listing example application",
    //     category: "Web App",
    //     image: "/assets/projects/house-listing-base.png",
    //     section: ['Frontend'],
    //     tags: ['TypeScript', 'Next.js', 'Real Estate'],
    //     featured: false,
    //     demoUrl: "https://house-listing-example.vercel.app",
    //     githubUrl: "https://github.com/Alaric-senpai/House-listing-example",
    //     otherimages: [],
    //     inDevelopment: false,
    //     rebranding: false,
    //     status: "Discontinued"
    // },
    // {
    //     id: 49,
    //     title: "Entertainment API",
    //     description: "An API for entertainment content",
    //     category: "Backend",
    //     image: "/assets/projects/entertainment-api-base.png",
    //     section: ['Backend'],
    //     tags: ['Python', 'API', 'Entertainment'],
    //     featured: false,
    //     demoUrl: "https://entertainment-api-lilac.vercel.app",
    //     githubUrl: "https://github.com/Alaric-senpai/Entertainment-api",
    //     otherimages: [],
    //     inDevelopment: false,
    //     rebranding: false,
    //     status: "Discontinued"
    // },
    // {
    //     id: 50,
    //     title: "Fake Store",
    //     description: "A demo e-commerce store using Fake Store API",
    //     category: "Web App",
    //     image: "/assets/projects/fakestore-base.png",
    //     section: ['Frontend'],
    //     tags: ['TypeScript', 'Next.js', 'E-commerce', 'API'],
    //     featured: false,
    //     demoUrl: "https://fakestore-mu-six.vercel.app",
    //     githubUrl: "https://github.com/Alaric-senpai/fakestore",
    //     otherimages: [],
    //     inDevelopment: false,
    //     rebranding: false,
    //     status: "Discontinued"
    // },
    {
        id: 51,
        title: "Maplewood",
        description: "A PHP-based web application",
        category: "Web App",
        image: "/assets/projects/preview-missing.png",
        section: ['Frontend', 'Backend'],
        tags: ['PHP', 'MySQL'],
        featured: false,
        demoUrl: "",
        githubUrl: "https://github.com/Alaric-senpai/maplewood",
        otherimages: [],
        inDevelopment: false,
        rebranding: false,
        status: "Discontinued"
    }
]

export const projects = activeProjects


export const personalLinks = {
    github:"https://github.com/Alaric-senpai",
    linkedin:"https://www.linkedin.com/in/kahuho-charles-86675e",
    twitter:"https://x.com/Alaric_kagenou"
}